// Bilingual UI strings. Arabic is the primary language; English is a full alternative.
const dict = {
  ar: {
    'app.name': 'التوأم الرقمي لمحطات الطاقة في الوطن العربي', 'app.short': 'Arab Power Twin', 'app.tagline': 'محاكاة تعليمية لمحطات طاقة حقيقية في 22 دولة عربية',
    'common.save': 'حفظ', 'common.cancel': 'إلغاء', 'common.close': 'إغلاق', 'common.delete': 'حذف', 'common.edit': 'تعديل', 'common.add': 'إضافة', 'common.create': 'إنشاء', 'common.search': 'بحث…', 'common.all': 'الكل', 'common.yes': 'نعم', 'common.no': 'لا', 'common.ok': 'موافق', 'common.back': 'رجوع', 'common.next': 'التالي', 'common.previous': 'السابق', 'common.loading': 'جارٍ التحميل…', 'common.none': 'لا يوجد', 'common.export': 'تصدير', 'common.exportCsv': 'تصدير CSV (Excel)', 'common.exportJson': 'تصدير JSON', 'common.exportPdf': 'تصدير PDF', 'common.print': 'طباعة', 'common.refresh': 'تحديث', 'common.confirm': 'تأكيد', 'common.confirmDelete': 'هل أنت متأكد من الحذف؟ لا يمكن التراجع.', 'common.saved': 'تم الحفظ', 'common.error': 'حدث خطأ', 'common.copied': 'تم النسخ', 'common.copy': 'نسخ', 'common.details': 'التفاصيل', 'common.name': 'الاسم', 'common.actions': 'إجراءات', 'common.status': 'الحالة', 'common.date': 'التاريخ', 'common.optional': '(اختياري)', 'common.required': 'مطلوب', 'common.unknown': 'غير معروف', 'common.total': 'الإجمالي', 'common.count': 'العدد', 'common.of': 'من', 'common.rows': 'صف', 'common.page': 'صفحة', 'common.noResults': 'لا توجد نتائج مطابقة', 'common.showing': 'عرض {a}–{b} من {n}', 'common.download': 'تنزيل', 'common.open': 'فتح', 'common.apply': 'تطبيق', 'common.reset': 'إعادة ضبط', 'common.language': 'اللغة', 'common.theme': 'المظهر', 'common.dark': 'داكن', 'common.light': 'فاتح', 'common.min': 'دقيقة', 'common.sec': 'ث', 'common.hours': 'ساعة', 'common.mw': 'ميغاواط', 'common.gwh': 'غ.و.س', 'common.year': 'السنة', 'common.country': 'الدولة', 'common.fuel': 'مصدر الطاقة', 'common.technology': 'التقنية', 'common.capacity': 'القدرة', 'common.owner': 'المالك / المشغل', 'common.source': 'المصدر', 'common.savedTo': 'تم الحفظ في: {path}', 'common.showInFolder': 'إظهار في المجلد', 'common.exportFailed': 'فشل التصدير',
    'nav.dashboard': 'لوحة المعلومات', 'nav.plants': 'مستكشف المحطات', 'nav.map': 'الخريطة', 'nav.twin': 'التوأم الرقمي', 'nav.exams': 'الاختبارات', 'nav.practice': 'تدريب ذاتي', 'nav.results': 'نتائجي', 'nav.profile': 'حسابي', 'nav.about': 'حول البرنامج', 'nav.admin': 'الإدارة', 'nav.users': 'المستخدمون', 'nav.groups': 'المجموعات / الشُعب', 'nav.examsAdmin': 'إدارة الاختبارات', 'nav.resultsAdmin': 'النتائج والتقييم', 'nav.sessions': 'جلسات المحاكاة', 'nav.license': 'الترخيص', 'nav.settings': 'الإعدادات', 'nav.updates': 'التحديثات', 'nav.workspace': 'البيانات والنسخ الاحتياطي', 'nav.audit': 'سجل النشاط', 'nav.logout': 'تسجيل الخروج', 'nav.learn': 'التعلم', 'nav.system': 'النظام',
    'role.superadmin': 'مشرف عام', 'role.instructor': 'مدرّس', 'role.student': 'طالب',
    'activation.title': 'تفعيل الترخيص', 'activation.intro': 'أدخل مفتاح الترخيص الذي حصلت عليه من المورد لتفعيل البرنامج على هذا الجهاز.', 'activation.key': 'مفتاح الترخيص', 'activation.paste': 'الصق المفتاح هنا (يبدأ بـ APT1.)', 'activation.activate': 'تفعيل', 'activation.loadFile': 'تحميل من ملف .lic', 'activation.machineId': 'معرّف هذا الجهاز', 'activation.machineHelp': 'أرسل هذا المعرّف للمورد إذا كان الترخيص مرتبطاً بجهاز محدد.', 'activation.success': 'تم تفعيل الترخيص بنجاح', 'activation.devNotice': 'وضع التطوير: تُقبل مفاتيح التطوير أيضاً.', 'activation.noProdKey': 'تنبيه للمورد: لم يتم تضمين مفتاح الإنتاج العام بعد (npm run license -- keygen).', 'activation.contact': 'للحصول على اشتراك أو تجديده تواصل مع شركة أصفان.',
    'license.valid': 'الترخيص صالح', 'license.invalid': 'الترخيص غير صالح', 'license.type': 'نوع الترخيص', 'license.plan.monthly': 'اشتراك شهري', 'license.plan.yearly': 'اشتراك سنوي', 'license.plan.custom': 'اشتراك محدد المدة', 'license.plan.staff': 'ترخيص داخلي', 'license.renew': 'لتجديد الاشتراك تواصل مع شركة أصفان ثم فعّل المفتاح الجديد من صفحة الترخيص.', 'license.expires': 'تاريخ الانتهاء', 'license.daysLeft': 'الأيام المتبقية', 'license.licensee': 'المرخَّص له', 'license.org': 'الجهة', 'license.seats': 'عدد المقاعد', 'license.issued': 'تاريخ الإصدار', 'license.id': 'رقم الترخيص', 'license.machineLock': 'مرتبط بالجهاز', 'license.remove': 'إزالة الترخيص', 'license.replace': 'تفعيل مفتاح جديد', 'license.expiringSoon': 'ينتهي الاشتراك خلال {n} يوماً. تواصل مع شركة أصفان للتجديد.', 'license.reason.missing': 'لا يوجد ترخيص مفعّل', 'license.reason.malformed': 'صيغة المفتاح غير صحيحة', 'license.reason.bad_signature': 'توقيع المفتاح غير صحيح (مفتاح مزوّر أو غير مطابق للإصدار)', 'license.reason.wrong_product': 'المفتاح لمنتج آخر', 'license.reason.machine_mismatch': 'هذا المفتاح مرتبط بجهاز آخر', 'license.reason.expired': 'انتهى الاشتراك. تواصل مع شركة أصفان للتجديد ثم أدخل المفتاح الجديد', 'license.reason.clock_tampered': 'تم اكتشاف تغيير في ساعة النظام؛ أعد ضبط التاريخ الصحيح', 'license.reason.no_public_key': 'لم يُضمَّن مفتاح التحقق في هذا الإصدار', 'license.modules': 'الوحدات المشمولة', 'license.technologies': 'التقنيات المشمولة', 'license.allTechnologies': 'جميع التقنيات', 'license.unlimited': 'غير محدود', 'license.lockedTech': 'هذه التقنية غير مشمولة في ترخيصكم. تواصل مع المورد لترقية الترخيص.', 'license.lockedModule': 'هذه الوحدة غير مشمولة في ترخيصكم.', 'license.locked': 'مقفل', 'module.twin': 'التوأم الرقمي', 'module.exams': 'الاختبارات والتقييم', 'license.seatsUsed': 'الحسابات المستخدمة',
    'setup.title': 'الإعداد الأولي', 'setup.intro': 'أنشئ حساب المشرف العام (مثل مدرّس المقرر أو مسؤول الجهة). سيتمكن هذا الحساب من إضافة الطلاب والمدرّسين والاطلاع على جميع النتائج.', 'setup.institution': 'اسم الجهة (جامعة / شركة)', 'setup.username': 'اسم المستخدم', 'setup.displayName': 'الاسم الكامل', 'setup.password': 'كلمة المرور', 'setup.password2': 'تأكيد كلمة المرور', 'setup.create': 'إنشاء الحساب والبدء', 'setup.mismatch': 'كلمتا المرور غير متطابقتين',
    'login.title': 'تسجيل الدخول', 'login.username': 'اسم المستخدم', 'login.password': 'كلمة المرور', 'login.submit': 'دخول', 'login.workspace': 'مجلد البيانات', 'login.licensedTo': 'مرخّص لـ',
    'dash.welcome': 'مرحباً {name}', 'dash.plants': 'محطة طاقة حقيقية', 'dash.countries': 'دولة عربية', 'dash.capacity': 'قدرة تشغيلية مسجلة', 'dash.renewables': 'طاقة متجددة', 'dash.featured': 'محطات مميزة بنموذج ثلاثي الأبعاد', 'dash.byCountry': 'القدرة التشغيلية حسب الدولة (ميغاواط)', 'dash.byFuel': 'توزيع القدرة حسب مصدر الطاقة', 'dash.myExams': 'اختباراتي المتاحة', 'dash.recentResults': 'آخر النتائج', 'dash.classStats': 'إحصاءات الطلاب', 'dash.students': 'طالب', 'dash.attempts': 'محاولة اختبار', 'dash.avg': 'متوسط الدرجات', 'dash.passRate': 'نسبة النجاح', 'dash.openTwin': 'افتح التوأم الرقمي', 'dash.startExam': 'ابدأ', 'dash.noExams': 'لا توجد اختبارات مسندة حالياً', 'dash.quickStart': 'ابدأ من هنا', 'dash.quick.explore': 'استكشف 600+ محطة على الخريطة', 'dash.quick.twin': 'شغّل محاكاة محطة حقيقية', 'dash.quick.practice': 'اختبر نفسك بأسئلة تدريبية', 'dash.dataNote': 'البيانات من قاعدة WRI العالمية وإضافات منسّقة حتى {date}',
    'plants.title': 'مستكشف محطات الطاقة', 'plants.subtitle': '{n} محطة في {c} دولة عربية – بيانات حقيقية من مصادر عامة', 'plants.filterCountry': 'الدولة', 'plants.filterFuel': 'مصدر الطاقة', 'plants.filterTech': 'التقنية', 'plants.filterStatus': 'الحالة', 'plants.minCapacity': 'الحد الأدنى للقدرة', 'plants.sort': 'ترتيب', 'plants.sortCapacity': 'القدرة', 'plants.sortName': 'الاسم', 'plants.sortYear': 'سنة التشغيل', 'plants.hero': 'نموذج 3D', 'plants.view.list': 'قائمة', 'plants.view.cards': 'بطاقات', 'plants.matching': '{n} محطة مطابقة – {mw} ميغاواط', 'plants.mapHint': 'انقر على نقطة في الخريطة لعرض المحطة، واسحب للتحريك، وعجلة الفأرة للتكبير',
    'status.operational': 'تعمل', 'status.under_construction': 'قيد الإنشاء', 'status.planned': 'مخططة', 'status.decommissioned': 'خارج الخدمة',
    'quality.gppd': 'WRI GPPD', 'quality.verified': 'موثّق', 'quality.approximate': 'تقريبي', 'quality.aggregate-estimate': 'تقدير مجمّع',
    'plant.overview': 'نظرة عامة', 'plant.technology': 'التقنية', 'plant.location': 'الموقع', 'plant.coordinates': 'الإحداثيات', 'plant.commissioned': 'سنة التشغيل', 'plant.units': 'الوحدات', 'plant.generation': 'الإنتاج السنوي المسجل (غ.و.س)', 'plant.estimated': 'الإنتاج التقديري (غ.و.س)', 'plant.notes': 'ملاحظات', 'plant.facts': 'حقائق أساسية', 'plant.components': 'المكونات الرئيسية', 'plant.complex': 'جزء من مجمع', 'plant.members': 'محطات المجمع', 'plant.openTwin': 'تشغيل التوأم الرقمي', 'plant.practice': 'اختبار تدريبي عن هذه المحطة', 'plant.dataQuality': 'جودة البيانات', 'plant.sourceLink': 'رابط المصدر', 'plant.typicalCf': 'معامل القدرة النموذجي', 'plant.efficiency': 'الكفاءة النموذجية', 'plant.co2': 'معامل الانبعاث', 'plant.estimatedAnnual': 'الإنتاج السنوي التقديري بمعامل القدرة النموذجي', 'plant.nearby': 'محطات قريبة', 'plant.km': 'كم',
    'twin.title': 'التوأم الرقمي', 'twin.start': 'تشغيل', 'twin.pause': 'إيقاف مؤقت', 'twin.reset': 'إعادة', 'twin.speed': 'سرعة الزمن', 'twin.setpoint': 'نقطة ضبط الحمل', 'twin.ambient': 'درجة الحرارة المحيطة', 'twin.cloud': 'الغيوم', 'twin.wind': 'سرعة الرياح', 'twin.flow': 'التصريف المائي', 'twin.head': 'الارتفاع الصافي', 'twin.unit': 'وحدة', 'twin.units': 'الوحدات', 'twin.startUnit': 'تشغيل', 'twin.stopUnit': 'إيقاف', 'twin.output': 'الإنتاج', 'twin.load': 'الحمل', 'twin.efficiency': 'الكفاءة', 'twin.fuel': 'استهلاك الوقود', 'twin.co2': 'انبعاثات CO₂', 'twin.energy': 'الطاقة المتراكمة', 'twin.frequency': 'تردد الشبكة', 'twin.temp': 'الحرارة', 'twin.pressure': 'الضغط', 'twin.irradiance': 'الإشعاع الشمسي', 'twin.sunElevation': 'ارتفاع الشمس', 'twin.storage': 'مخزون الحرارة', 'twin.reservoir': 'منسوب الخزان', 'twin.alarms': 'الإنذارات والأحداث', 'twin.noAlarms': 'لا توجد إنذارات', 'twin.scenario': 'سيناريوهات تعليمية', 'twin.scenario.trip': 'فصل وحدة مفاجئ', 'twin.scenario.heat': 'موجة حر 48°م', 'twin.scenario.dust': 'عاصفة غبار', 'twin.scenario.gust': 'هبّة رياح قوية', 'twin.scenario.demand': 'قفزة في الطلب', 'twin.scenario.clear': 'إلغاء السيناريو', 'twin.kpis': 'مؤشرات الأداء', 'twin.capacityFactor': 'معامل القدرة (الجلسة)', 'twin.availability': 'التوافر', 'twin.trips': 'عدد الفصلات', 'twin.simTime': 'زمن المحاكاة', 'twin.trend': 'منحنى الإنتاج (ميغاواط)', 'twin.trend2': 'منحنى الكفاءة / الظروف', 'twin.camera': 'الكاميرا', 'twin.orbit': 'دوران تلقائي', 'twin.labels': 'تسميات', 'twin.endSession': 'إنهاء الجلسة وحفظ التقرير', 'twin.sessionSaved': 'تم حفظ جلسة المحاكاة في سجلك', 'twin.demand': 'الطلب من الشبكة', 'twin.gridHz': 'هرتز', 'twin.tripReason': 'سبب الفصل', 'twin.hint': 'استخدم الفأرة للدوران والتكبير. غيّر نقطة الضبط والظروف الجوية وراقب استجابة المحطة.', 'twin.model': 'النموذج ثلاثي الأبعاد', 'twin.generic': 'نموذج عام للتقنية', 'twin.heroModel': 'نموذج مخصص للمحطة', 'twin.stateOff': 'متوقفة', 'twin.stateStarting': 'إقلاع', 'twin.stateOn': 'تعمل', 'twin.stateTrip': 'مفصولة', 'twin.stateStopping': 'إيقاف', 'twin.hourOfDay': 'الساعة',
    'exams.title': 'الاختبارات', 'exams.available': 'الاختبارات المتاحة', 'exams.questions': 'سؤال', 'exams.duration': 'المدة', 'exams.passMark': 'درجة النجاح', 'exams.attempts': 'المحاولات', 'exams.attemptsUsed': '{a} من {b}', 'exams.unlimited': 'غير محدود', 'exams.start': 'بدء الاختبار', 'exams.resume': 'متابعة الاختبار', 'exams.noneAssigned': 'لا توجد اختبارات مسندة لك حالياً.', 'exams.startConfirm': 'سيبدأ العد التنازلي فور بدء الاختبار. هل تريد البدء الآن؟', 'exams.submit': 'تسليم الإجابات', 'exams.submitConfirm': 'لديك {n} سؤالاً بدون إجابة. هل تريد التسليم؟', 'exams.timeLeft': 'الوقت المتبقي', 'exams.question': 'سؤال {i} من {n}', 'exams.answered': 'تمت الإجابة على {a} من {n}', 'exams.autoSaved': 'تم الحفظ تلقائياً', 'exams.timeUp': 'انتهى الوقت – تم تسليم إجاباتك تلقائياً', 'exams.result': 'النتيجة', 'exams.passed': 'ناجح', 'exams.failed': 'راسب', 'exams.score': 'الدرجة', 'exams.review': 'مراجعة الإجابات', 'exams.yourAnswer': 'إجابتك', 'exams.correctAnswer': 'الإجابة الصحيحة', 'exams.explanation': 'الشرح', 'exams.generatedQ': 'سؤال مولّد من بيانات حقيقية', 'exams.byTopic': 'الأداء حسب الموضوع', 'exams.practiceTitle': 'اختبار تدريبي', 'exams.practiceIntro': 'اختبر معلوماتك بأسئلة من بنك الأسئلة وأسئلة مولّدة من بيانات المحطات الحقيقية. لا تُحتسب النتائج في التقييم الرسمي لكنها تُحفظ في سجلك.', 'exams.topics': 'الموضوعات', 'exams.numQuestions': 'عدد الأسئلة', 'exams.generatedShare': 'نسبة الأسئلة المولّدة من بيانات المحطات', 'exams.scopeCountries': 'الدول (لأسئلة المحطات)', 'exams.startPractice': 'ابدأ التدريب', 'exams.late': 'متأخر', 'exams.time': 'الوقت المستغرق', 'exams.attemptNo': 'محاولة رقم', 'exams.noQuestions': 'لا توجد أسئلة كافية للإعدادات المختارة',
    'results.title': 'نتائجي', 'results.intro': 'جميع محاولاتك في الاختبارات الرسمية والتدريبية.', 'results.exam': 'الاختبار', 'results.none': 'لم تُجرِ أي اختبار بعد.', 'results.certificate': 'شهادة / تقرير PDF', 'results.kind.exam': 'رسمي', 'results.kind.practice': 'تدريبي',
    'admin.users.title': 'إدارة المستخدمين', 'admin.users.add': 'إضافة مستخدم', 'admin.users.import': 'استيراد طلاب من CSV', 'admin.users.importHelp': 'أعمدة الملف: username,password,displayName,studentNumber,groupName,email – (السطر الأول عناوين اختيارية). كلمة المرور الافتراضية student123 إن تُركت فارغة، ويُطلب من الطالب تغييرها عند أول دخول.', 'admin.users.username': 'اسم المستخدم', 'admin.users.displayName': 'الاسم', 'admin.users.role': 'الدور', 'admin.users.group': 'المجموعة', 'admin.users.studentNumber': 'الرقم الجامعي', 'admin.users.email': 'البريد', 'admin.users.active': 'نشط', 'admin.users.inactive': 'موقوف', 'admin.users.lastLogin': 'آخر دخول', 'admin.users.password': 'كلمة المرور', 'admin.users.resetPassword': 'إعادة تعيين كلمة المرور', 'admin.users.newPassword': 'كلمة المرور الجديدة', 'admin.users.deactivate': 'إيقاف', 'admin.users.activate': 'تنشيط', 'admin.users.viewResults': 'عرض النتائج', 'admin.users.imported': 'تم إنشاء {c} حساباً، وتخطي {s}', 'admin.users.created': 'تم إنشاء المستخدم', 'admin.users.selectFile': 'اختيار ملف CSV', 'admin.users.pasteCsv': 'أو الصق محتوى CSV هنا',
    'admin.groups.title': 'المجموعات / الشُعب الدراسية', 'admin.groups.add': 'إضافة مجموعة', 'admin.groups.desc': 'الوصف', 'admin.groups.members': 'الأعضاء',
    'admin.exams.title': 'إدارة الاختبارات', 'admin.exams.add': 'اختبار جديد', 'admin.exams.titleEn': 'العنوان (إنجليزي)', 'admin.exams.titleAr': 'العنوان (عربي)', 'admin.exams.description': 'وصف / تعليمات', 'admin.exams.topics': 'موضوعات بنك الأسئلة', 'admin.exams.questionCount': 'عدد الأسئلة', 'admin.exams.generatedShare': 'نسبة الأسئلة المولّدة من بيانات المحطات الحقيقية', 'admin.exams.scope': 'نطاق المحطات للأسئلة المولّدة', 'admin.exams.duration': 'المدة (دقائق)', 'admin.exams.passMark': 'درجة النجاح (%)', 'admin.exams.maxAttempts': 'الحد الأقصى للمحاولات (0 = غير محدود)', 'admin.exams.groups': 'المجموعات المسندة (فارغ = جميع الطلاب)', 'admin.exams.showAnswers': 'إظهار الإجابات الصحيحة للطالب بعد التسليم', 'admin.exams.shuffle': 'خلط الأسئلة', 'admin.exams.active': 'مفعّل', 'admin.exams.bankAvailable': 'الأسئلة المتاحة في البنك للموضوعات المختارة: {n}', 'admin.exams.attemptsCount': 'المحاولات', 'admin.exams.avg': 'المتوسط', 'admin.exams.created': 'تم إنشاء الاختبار', 'admin.exams.techScope': 'التقنيات',
    'admin.results.title': 'النتائج والتقييم', 'admin.results.intro': 'جميع محاولات الطلاب مع إحصاءات وتصدير للملفات.', 'admin.results.filterExam': 'الاختبار', 'admin.results.filterGroup': 'المجموعة', 'admin.results.filterStudent': 'الطالب', 'admin.results.filterKind': 'النوع', 'admin.results.student': 'الطالب', 'admin.results.mean': 'المتوسط', 'admin.results.median': 'الوسيط', 'admin.results.passRate': 'نسبة النجاح', 'admin.results.distribution': 'توزيع الدرجات', 'admin.results.byExam': 'حسب الاختبار', 'admin.results.byTopic': 'نسبة الإجابات الصحيحة حسب الموضوع', 'admin.results.exportAll': 'تصدير النتائج المعروضة', 'admin.results.studentReport': 'تقرير الطالب', 'admin.results.perStudent': 'ملخص لكل طالب', 'admin.results.best': 'أفضل درجة', 'admin.results.last': 'آخر محاولة', 'admin.results.attempts': 'المحاولات', 'admin.results.noData': 'لا توجد محاولات مطابقة',
    'admin.sessions.title': 'جلسات المحاكاة', 'admin.sessions.intro': 'سجل تدريب الطلاب على التوأم الرقمي: المحطة، المدة، ومؤشرات الأداء.', 'admin.sessions.plant': 'المحطة', 'admin.sessions.duration': 'المدة', 'admin.sessions.energy': 'الطاقة المولدة', 'admin.sessions.cf': 'معامل القدرة', 'admin.sessions.trips': 'الفصلات',
    'admin.settings.title': 'الإعدادات', 'admin.settings.institution': 'اسم الجهة', 'admin.settings.workspace': 'مجلد البيانات المشترك', 'admin.settings.workspaceHelp': 'يُخزَّن المستخدمون والنتائج في هذا المجلد. لمشاركة البيانات بين أجهزة معمل الجامعة اختر مجلداً على الشبكة (مثل \\\\server\\ArabPowerTwin) واستخدم نفس المجلد على كل جهاز.', 'admin.settings.choose': 'اختيار مجلد…', 'admin.settings.useDefault': 'استخدام المجلد الافتراضي', 'admin.settings.workspaceChanged': 'تم تغيير مجلد البيانات. سجّل الدخول من جديد.', 'admin.settings.updateFeed': 'رابط خادم التحديثات (اختياري)', 'admin.settings.updateFeedHelp': 'اتركه فارغاً لاستخدام إصدارات GitHub الرسمية. يمكن وضع رابط HTTPS لمجلد يحتوي latest.yml والمثبّت.', 'admin.settings.autoCheck': 'التحقق التلقائي من التحديثات عند التشغيل', 'admin.settings.restartNote': 'تُطبَّق إعدادات التحديث بعد إعادة تشغيل البرنامج.',
    'updates.title': 'التحديثات', 'updates.current': 'الإصدار الحالي', 'updates.check': 'التحقق من وجود تحديث', 'updates.available': 'يتوفر تحديث جديد: الإصدار {v}', 'updates.download': 'تنزيل التحديث', 'updates.downloading': 'جارٍ التنزيل… {p}%', 'updates.downloaded': 'تم تنزيل الإصدار {v} – أعد التشغيل للتثبيت', 'updates.install': 'إعادة التشغيل والتثبيت', 'updates.upToDate': 'أنت تستخدم أحدث إصدار', 'updates.checking': 'جارٍ التحقق…', 'updates.error': 'تعذر التحقق من التحديثات: {e}', 'updates.disabledDev': 'التحديث التلقائي يعمل فقط في النسخة المثبّتة (exe).', 'updates.how': 'كيف تعمل التحديثات؟', 'updates.howText': 'عند تشغيل البرنامج يتحقق من خادم الإصدارات؛ إذا وُجد إصدار أحدث يظهر إشعار هنا وفي أعلى الشاشة، ويمكن تنزيله وتثبيته بنقرة واحدة دون فقدان البيانات.', 'updates.releaseNotes': 'ملاحظات الإصدار', 'updates.later': 'لاحقاً',
    'workspace.title': 'البيانات والنسخ الاحتياطي', 'workspace.dir': 'مجلد البيانات', 'workspace.records': 'السجلات', 'workspace.backup': 'تصدير نسخة احتياطية كاملة (JSON)', 'workspace.restore': 'استعادة من نسخة احتياطية', 'workspace.restoreMode': 'طريقة الاستعادة', 'workspace.merge': 'دمج (لا يستبدل السجلات الموجودة)', 'workspace.overwrite': 'استبدال السجلات المطابقة', 'workspace.restored': 'تمت استعادة {n} سجلاً', 'workspace.error': 'تعذر الوصول إلى مجلد البيانات المحدد، تم استخدام المجلد المحلي مؤقتاً: {e}', 'workspace.users': 'مستخدمون', 'workspace.groups': 'مجموعات', 'workspace.exams': 'اختبارات', 'workspace.attempts': 'محاولات', 'workspace.sessions': 'جلسات محاكاة',
    'audit.title': 'سجل النشاط', 'audit.action': 'الإجراء', 'audit.by': 'بواسطة', 'audit.details': 'التفاصيل',
    'profile.title': 'حسابي', 'profile.changePassword': 'تغيير كلمة المرور', 'profile.old': 'كلمة المرور الحالية', 'profile.new': 'كلمة المرور الجديدة', 'profile.changed': 'تم تغيير كلمة المرور', 'profile.mustChange': 'يجب تغيير كلمة المرور المؤقتة قبل المتابعة.', 'profile.group': 'المجموعة', 'profile.sessions': 'جلسات المحاكاة الخاصة بي',
    'about.title': 'حول البرنامج', 'about.version': 'الإصدار', 'about.data': 'مصادر البيانات', 'about.dataText': 'تعتمد قاعدة المحطات على قاعدة بيانات WRI العالمية لمحطات الطاقة (الإصدار 1.3.0، ترخيص CC BY 4.0) مضافاً إليها محطات حديثة (2019–2026) منسّقة من منشورات المشغلين والمرافق (ديوا، EWEC، الشركة السعودية للكهرباء، الشركة القابضة لكهرباء مصر، مازن، نواة…) ووكالة IRENA والبيانات الصحفية. الخريطة من Natural Earth (ملكية عامة). الخط: Cairo (رخصة OFL).', 'about.disclaimer': 'إخلاء مسؤولية', 'about.disclaimerText': 'هذا برنامج تعليمي. نماذج المحاكاة مبسّطة تعتمد على معاملات نموذجية لكل تقنية وليست بيانات تشغيل حية، والقدرات والتواريخ قد تختلف عن الواقع الحالي. لا يُستخدم لأي غرض تشغيلي فعلي.', 'about.machine': 'معرّف الجهاز', 'about.workspace': 'مجلد البيانات', 'about.plants': 'عدد المحطات', 'about.techs': 'التقنيات المدعومة',
    'errors.bad_credentials': 'اسم المستخدم أو كلمة المرور غير صحيحة', 'errors.not_authenticated': 'يجب تسجيل الدخول', 'errors.forbidden': 'ليست لديك صلاحية لهذا الإجراء', 'errors.username_taken': 'اسم المستخدم مستخدم مسبقاً', 'errors.invalid_username': 'اسم المستخدم غير صالح (3–64 حرفاً لاتينياً أو رقماً)', 'errors.weak_password': 'كلمة المرور قصيرة (6 أحرف على الأقل)', 'errors.invalid_role': 'الدور غير صالح', 'errors.not_found': 'العنصر غير موجود', 'errors.last_superadmin': 'لا يمكن إزالة آخر مشرف عام', 'errors.license_required': 'يجب تفعيل الترخيص أولاً', 'errors.already_setup': 'تم الإعداد مسبقاً', 'errors.max_attempts': 'استنفدت عدد المحاولات المسموح بها', 'errors.already_submitted': 'تم تسليم هذه المحاولة مسبقاً', 'errors.title_required': 'العنوان مطلوب', 'errors.name_required': 'الاسم مطلوب', 'errors.bad_question_count': 'عدد الأسئلة غير صالح (1–200)', 'errors.bad_duration': 'المدة غير صالحة', 'errors.bad_pass_mark': 'درجة النجاح غير صالحة', 'errors.channel_not_allowed': 'قناة غير مسموحة', 'errors.seats_exceeded': 'تم بلوغ الحد الأقصى لعدد الحسابات المسموح به في الترخيص', 'errors.module_locked': 'هذه الوحدة غير مشمولة في الترخيص', 'errors.tech_locked': 'هذه التقنية غير مشمولة في الترخيص', 'errors.bad_url': 'رابط غير صالح', 'errors.generic': 'حدث خطأ: {e}',
  },
  en: {
    'app.name': 'Digital Twin of Power Plants in the Arab World', 'app.short': 'Arab Power Twin', 'app.tagline': 'Educational simulation of real power plants across 22 Arab countries',
    'common.save': 'Save', 'common.cancel': 'Cancel', 'common.close': 'Close', 'common.delete': 'Delete', 'common.edit': 'Edit', 'common.add': 'Add', 'common.create': 'Create', 'common.search': 'Search…', 'common.all': 'All', 'common.yes': 'Yes', 'common.no': 'No', 'common.ok': 'OK', 'common.back': 'Back', 'common.next': 'Next', 'common.previous': 'Previous', 'common.loading': 'Loading…', 'common.none': 'None', 'common.export': 'Export', 'common.exportCsv': 'Export CSV (Excel)', 'common.exportJson': 'Export JSON', 'common.exportPdf': 'Export PDF', 'common.print': 'Print', 'common.refresh': 'Refresh', 'common.confirm': 'Confirm', 'common.confirmDelete': 'Delete permanently? This cannot be undone.', 'common.saved': 'Saved', 'common.error': 'Something went wrong', 'common.copied': 'Copied', 'common.copy': 'Copy', 'common.details': 'Details', 'common.name': 'Name', 'common.actions': 'Actions', 'common.status': 'Status', 'common.date': 'Date', 'common.optional': '(optional)', 'common.required': 'required', 'common.unknown': 'unknown', 'common.total': 'Total', 'common.count': 'Count', 'common.of': 'of', 'common.rows': 'rows', 'common.page': 'Page', 'common.noResults': 'No matching results', 'common.showing': 'Showing {a}–{b} of {n}', 'common.download': 'Download', 'common.open': 'Open', 'common.apply': 'Apply', 'common.reset': 'Reset', 'common.language': 'Language', 'common.theme': 'Theme', 'common.dark': 'Dark', 'common.light': 'Light', 'common.min': 'min', 'common.sec': 's', 'common.hours': 'h', 'common.mw': 'MW', 'common.gwh': 'GWh', 'common.year': 'Year', 'common.country': 'Country', 'common.fuel': 'Energy source', 'common.technology': 'Technology', 'common.capacity': 'Capacity', 'common.owner': 'Owner / operator', 'common.source': 'Source', 'common.savedTo': 'Saved to: {path}', 'common.showInFolder': 'Show in folder', 'common.exportFailed': 'Export failed',
    'nav.dashboard': 'Dashboard', 'nav.plants': 'Plant explorer', 'nav.map': 'Map', 'nav.twin': 'Digital twin', 'nav.exams': 'Exams', 'nav.practice': 'Practice quiz', 'nav.results': 'My results', 'nav.profile': 'My account', 'nav.about': 'About', 'nav.admin': 'Administration', 'nav.users': 'Users', 'nav.groups': 'Groups / classes', 'nav.examsAdmin': 'Exam management', 'nav.resultsAdmin': 'Results & assessment', 'nav.sessions': 'Simulation sessions', 'nav.license': 'License', 'nav.settings': 'Settings', 'nav.updates': 'Updates', 'nav.workspace': 'Data & backup', 'nav.audit': 'Activity log', 'nav.logout': 'Sign out', 'nav.learn': 'Learn', 'nav.system': 'System',
    'role.superadmin': 'Super admin', 'role.instructor': 'Instructor', 'role.student': 'Student',
    'activation.title': 'License activation', 'activation.intro': 'Enter the license key you received from the vendor to activate the software on this computer.', 'activation.key': 'License key', 'activation.paste': 'Paste the key here (starts with APT1.)', 'activation.activate': 'Activate', 'activation.loadFile': 'Load from .lic file', 'activation.machineId': 'This computer\'s ID', 'activation.machineHelp': 'Send this ID to the vendor if your license is locked to a specific computer.', 'activation.success': 'License activated successfully', 'activation.devNotice': 'Development mode: development keys are accepted too.', 'activation.noProdKey': 'Vendor notice: the production public key is not embedded yet (npm run license -- keygen).', 'activation.contact': 'Contact Asfan Co. to obtain or renew a subscription.',
    'license.valid': 'License valid', 'license.invalid': 'License invalid', 'license.type': 'License type', 'license.plan.monthly': 'Monthly subscription', 'license.plan.yearly': 'Annual subscription', 'license.plan.custom': 'Fixed-term subscription', 'license.plan.staff': 'Internal license', 'license.renew': 'To renew the subscription contact Asfan Co., then activate the new key on the License page.', 'license.expires': 'Expiry date', 'license.daysLeft': 'Days left', 'license.licensee': 'Licensee', 'license.org': 'Organisation', 'license.seats': 'Seats', 'license.issued': 'Issued', 'license.id': 'License ID', 'license.machineLock': 'Machine-locked', 'license.remove': 'Remove license', 'license.replace': 'Activate a new key', 'license.expiringSoon': 'The subscription expires in {n} days. Contact Asfan Co. to renew.', 'license.reason.missing': 'No license activated', 'license.reason.malformed': 'The key format is invalid', 'license.reason.bad_signature': 'Invalid signature (forged key or key for another build)', 'license.reason.wrong_product': 'The key belongs to another product', 'license.reason.machine_mismatch': 'This key is locked to another computer', 'license.reason.expired': 'The subscription has expired. Contact Asfan Co. to renew, then enter the new key', 'license.reason.clock_tampered': 'System clock rollback detected; restore the correct date', 'license.reason.no_public_key': 'No verification key is embedded in this build', 'license.modules': 'Included modules', 'license.technologies': 'Included technologies', 'license.allTechnologies': 'All technologies', 'license.unlimited': 'Unlimited', 'license.lockedTech': 'This technology is not included in your license. Contact the vendor to upgrade.', 'license.lockedModule': 'This module is not included in your license.', 'license.locked': 'Locked', 'module.twin': 'Digital twin', 'module.exams': 'Exams & assessment', 'license.seatsUsed': 'Accounts in use',
    'setup.title': 'Initial setup', 'setup.intro': 'Create the super-admin account (e.g. the course instructor or the organisation administrator). This account can add students and instructors and see every result.', 'setup.institution': 'Organisation name (university / company)', 'setup.username': 'Username', 'setup.displayName': 'Full name', 'setup.password': 'Password', 'setup.password2': 'Confirm password', 'setup.create': 'Create account and start', 'setup.mismatch': 'Passwords do not match',
    'login.title': 'Sign in', 'login.username': 'Username', 'login.password': 'Password', 'login.submit': 'Sign in', 'login.workspace': 'Data folder', 'login.licensedTo': 'Licensed to',
    'dash.welcome': 'Welcome, {name}', 'dash.plants': 'real power plants', 'dash.countries': 'Arab countries', 'dash.capacity': 'recorded operational capacity', 'dash.renewables': 'renewable capacity', 'dash.featured': 'Featured plants with 3D models', 'dash.byCountry': 'Operational capacity by country (MW)', 'dash.byFuel': 'Capacity by energy source', 'dash.myExams': 'My available exams', 'dash.recentResults': 'Recent results', 'dash.classStats': 'Student statistics', 'dash.students': 'students', 'dash.attempts': 'exam attempts', 'dash.avg': 'average score', 'dash.passRate': 'pass rate', 'dash.openTwin': 'Open digital twin', 'dash.startExam': 'Start', 'dash.noExams': 'No exams assigned right now', 'dash.quickStart': 'Start here', 'dash.quick.explore': 'Explore 600+ plants on the map', 'dash.quick.twin': 'Run a simulation of a real plant', 'dash.quick.practice': 'Test yourself with a practice quiz', 'dash.dataNote': 'Data from the WRI Global Power Plant Database plus curated additions up to {date}',
    'plants.title': 'Power plant explorer', 'plants.subtitle': '{n} plants in {c} Arab countries – real data from public sources', 'plants.filterCountry': 'Country', 'plants.filterFuel': 'Energy source', 'plants.filterTech': 'Technology', 'plants.filterStatus': 'Status', 'plants.minCapacity': 'Minimum capacity', 'plants.sort': 'Sort', 'plants.sortCapacity': 'Capacity', 'plants.sortName': 'Name', 'plants.sortYear': 'Commissioning year', 'plants.hero': '3D model', 'plants.view.list': 'List', 'plants.view.cards': 'Cards', 'plants.matching': '{n} matching plants – {mw} MW', 'plants.mapHint': 'Click a dot to open the plant, drag to pan, scroll to zoom',
    'status.operational': 'Operational', 'status.under_construction': 'Under construction', 'status.planned': 'Planned', 'status.decommissioned': 'Decommissioned',
    'quality.gppd': 'WRI GPPD', 'quality.verified': 'Verified', 'quality.approximate': 'Approximate', 'quality.aggregate-estimate': 'Aggregate estimate',
    'plant.overview': 'Overview', 'plant.technology': 'Technology', 'plant.location': 'Location', 'plant.coordinates': 'Coordinates', 'plant.commissioned': 'Commissioned', 'plant.units': 'Units', 'plant.generation': 'Recorded annual generation (GWh)', 'plant.estimated': 'Estimated generation (GWh)', 'plant.notes': 'Notes', 'plant.facts': 'Key facts', 'plant.components': 'Main components', 'plant.complex': 'Part of complex', 'plant.members': 'Plants in this complex', 'plant.openTwin': 'Run the digital twin', 'plant.practice': 'Practice quiz about this plant', 'plant.dataQuality': 'Data quality', 'plant.sourceLink': 'Source link', 'plant.typicalCf': 'Typical capacity factor', 'plant.efficiency': 'Typical efficiency', 'plant.co2': 'Emission factor', 'plant.estimatedAnnual': 'Estimated annual output at the typical capacity factor', 'plant.nearby': 'Nearby plants', 'plant.km': 'km',
    'twin.title': 'Digital twin', 'twin.start': 'Run', 'twin.pause': 'Pause', 'twin.reset': 'Reset', 'twin.speed': 'Time speed', 'twin.setpoint': 'Load setpoint', 'twin.ambient': 'Ambient temperature', 'twin.cloud': 'Cloud cover', 'twin.wind': 'Wind speed', 'twin.flow': 'Water discharge', 'twin.head': 'Net head', 'twin.unit': 'Unit', 'twin.units': 'Units', 'twin.startUnit': 'Start', 'twin.stopUnit': 'Stop', 'twin.output': 'Output', 'twin.load': 'Load', 'twin.efficiency': 'Efficiency', 'twin.fuel': 'Fuel consumption', 'twin.co2': 'CO₂ emissions', 'twin.energy': 'Energy delivered', 'twin.frequency': 'Grid frequency', 'twin.temp': 'Temperature', 'twin.pressure': 'Pressure', 'twin.irradiance': 'Solar irradiance', 'twin.sunElevation': 'Sun elevation', 'twin.storage': 'Thermal storage', 'twin.reservoir': 'Reservoir level', 'twin.alarms': 'Alarms & events', 'twin.noAlarms': 'No alarms', 'twin.scenario': 'Training scenarios', 'twin.scenario.trip': 'Sudden unit trip', 'twin.scenario.heat': 'Heat wave 48 °C', 'twin.scenario.dust': 'Dust storm', 'twin.scenario.gust': 'Strong wind gust', 'twin.scenario.demand': 'Demand surge', 'twin.scenario.clear': 'Clear scenario', 'twin.kpis': 'Performance indicators', 'twin.capacityFactor': 'Capacity factor (session)', 'twin.availability': 'Availability', 'twin.trips': 'Trips', 'twin.simTime': 'Simulation time', 'twin.trend': 'Output trend (MW)', 'twin.trend2': 'Efficiency / conditions', 'twin.camera': 'Camera', 'twin.orbit': 'Auto-orbit', 'twin.labels': 'Labels', 'twin.endSession': 'End session & save report', 'twin.sessionSaved': 'Simulation session saved to your record', 'twin.demand': 'Grid demand', 'twin.gridHz': 'Hz', 'twin.tripReason': 'Trip reason', 'twin.hint': 'Use the mouse to orbit and zoom. Change the setpoint and weather and watch the plant respond.', 'twin.model': '3D model', 'twin.generic': 'generic model for this technology', 'twin.heroModel': 'plant-specific model', 'twin.stateOff': 'Off', 'twin.stateStarting': 'Starting', 'twin.stateOn': 'Running', 'twin.stateTrip': 'Tripped', 'twin.stateStopping': 'Stopping', 'twin.hourOfDay': 'Hour',
    'exams.title': 'Exams', 'exams.available': 'Available exams', 'exams.questions': 'questions', 'exams.duration': 'Duration', 'exams.passMark': 'Pass mark', 'exams.attempts': 'Attempts', 'exams.attemptsUsed': '{a} of {b}', 'exams.unlimited': 'unlimited', 'exams.start': 'Start exam', 'exams.resume': 'Resume exam', 'exams.noneAssigned': 'No exams are assigned to you right now.', 'exams.startConfirm': 'The timer starts as soon as the exam begins. Start now?', 'exams.submit': 'Submit answers', 'exams.submitConfirm': 'You have {n} unanswered questions. Submit anyway?', 'exams.timeLeft': 'Time left', 'exams.question': 'Question {i} of {n}', 'exams.answered': '{a} of {n} answered', 'exams.autoSaved': 'Auto-saved', 'exams.timeUp': 'Time is up – your answers were submitted automatically', 'exams.result': 'Result', 'exams.passed': 'Passed', 'exams.failed': 'Failed', 'exams.score': 'Score', 'exams.review': 'Review answers', 'exams.yourAnswer': 'Your answer', 'exams.correctAnswer': 'Correct answer', 'exams.explanation': 'Explanation', 'exams.generatedQ': 'Generated from real plant data', 'exams.byTopic': 'Performance by topic', 'exams.practiceTitle': 'Practice quiz', 'exams.practiceIntro': 'Test yourself with questions from the bank and questions generated from real plant data. Results are not part of formal assessment but are kept in your record.', 'exams.topics': 'Topics', 'exams.numQuestions': 'Number of questions', 'exams.generatedShare': 'Share of questions generated from plant data', 'exams.scopeCountries': 'Countries (for plant questions)', 'exams.startPractice': 'Start practice', 'exams.late': 'Late', 'exams.time': 'Time taken', 'exams.attemptNo': 'Attempt', 'exams.noQuestions': 'Not enough questions for the selected settings',
    'results.title': 'My results', 'results.intro': 'All your formal and practice attempts.', 'results.exam': 'Exam', 'results.none': 'You have not taken any exam yet.', 'results.certificate': 'Certificate / PDF report', 'results.kind.exam': 'Formal', 'results.kind.practice': 'Practice',
    'admin.users.title': 'User management', 'admin.users.add': 'Add user', 'admin.users.import': 'Import students from CSV', 'admin.users.importHelp': 'Columns: username,password,displayName,studentNumber,groupName,email (an optional header row). Empty password defaults to student123 and the student must change it at first login.', 'admin.users.username': 'Username', 'admin.users.displayName': 'Name', 'admin.users.role': 'Role', 'admin.users.group': 'Group', 'admin.users.studentNumber': 'Student number', 'admin.users.email': 'Email', 'admin.users.active': 'Active', 'admin.users.inactive': 'Suspended', 'admin.users.lastLogin': 'Last login', 'admin.users.password': 'Password', 'admin.users.resetPassword': 'Reset password', 'admin.users.newPassword': 'New password', 'admin.users.deactivate': 'Suspend', 'admin.users.activate': 'Activate', 'admin.users.viewResults': 'View results', 'admin.users.imported': '{c} accounts created, {s} skipped', 'admin.users.created': 'User created', 'admin.users.selectFile': 'Choose CSV file', 'admin.users.pasteCsv': 'or paste CSV content here',
    'admin.groups.title': 'Groups / classes', 'admin.groups.add': 'Add group', 'admin.groups.desc': 'Description', 'admin.groups.members': 'Members',
    'admin.exams.title': 'Exam management', 'admin.exams.add': 'New exam', 'admin.exams.titleEn': 'Title (English)', 'admin.exams.titleAr': 'Title (Arabic)', 'admin.exams.description': 'Description / instructions', 'admin.exams.topics': 'Question-bank topics', 'admin.exams.questionCount': 'Number of questions', 'admin.exams.generatedShare': 'Share of questions generated from real plant data', 'admin.exams.scope': 'Plant scope for generated questions', 'admin.exams.duration': 'Duration (minutes)', 'admin.exams.passMark': 'Pass mark (%)', 'admin.exams.maxAttempts': 'Max attempts (0 = unlimited)', 'admin.exams.groups': 'Assigned groups (empty = all students)', 'admin.exams.showAnswers': 'Show correct answers to students after submission', 'admin.exams.shuffle': 'Shuffle questions', 'admin.exams.active': 'Active', 'admin.exams.bankAvailable': 'Bank questions available for the selected topics: {n}', 'admin.exams.attemptsCount': 'Attempts', 'admin.exams.avg': 'Average', 'admin.exams.created': 'Exam created', 'admin.exams.techScope': 'Technologies',
    'admin.results.title': 'Results & assessment', 'admin.results.intro': 'Every student attempt with statistics and file export.', 'admin.results.filterExam': 'Exam', 'admin.results.filterGroup': 'Group', 'admin.results.filterStudent': 'Student', 'admin.results.filterKind': 'Kind', 'admin.results.student': 'Student', 'admin.results.mean': 'Mean', 'admin.results.median': 'Median', 'admin.results.passRate': 'Pass rate', 'admin.results.distribution': 'Score distribution', 'admin.results.byExam': 'By exam', 'admin.results.byTopic': 'Correct answers by topic', 'admin.results.exportAll': 'Export displayed results', 'admin.results.studentReport': 'Student report', 'admin.results.perStudent': 'Per-student summary', 'admin.results.best': 'Best score', 'admin.results.last': 'Last attempt', 'admin.results.attempts': 'Attempts', 'admin.results.noData': 'No matching attempts',
    'admin.sessions.title': 'Simulation sessions', 'admin.sessions.intro': 'Record of student practice on the digital twin: plant, duration and KPIs.', 'admin.sessions.plant': 'Plant', 'admin.sessions.duration': 'Duration', 'admin.sessions.energy': 'Energy generated', 'admin.sessions.cf': 'Capacity factor', 'admin.sessions.trips': 'Trips',
    'admin.settings.title': 'Settings', 'admin.settings.institution': 'Organisation name', 'admin.settings.workspace': 'Shared data folder', 'admin.settings.workspaceHelp': 'Users and results are stored in this folder. To share data across lab computers choose a network folder (e.g. \\\\server\\ArabPowerTwin) and use the same folder on every computer.', 'admin.settings.choose': 'Choose folder…', 'admin.settings.useDefault': 'Use default folder', 'admin.settings.workspaceChanged': 'Data folder changed. Please sign in again.', 'admin.settings.updateFeed': 'Update server URL (optional)', 'admin.settings.updateFeedHelp': 'Leave empty to use the official GitHub releases. Or set an HTTPS folder URL containing latest.yml and the installer.', 'admin.settings.autoCheck': 'Check for updates automatically at start-up', 'admin.settings.restartNote': 'Update settings take effect after restarting the application.',
    'updates.title': 'Updates', 'updates.current': 'Current version', 'updates.check': 'Check for updates', 'updates.available': 'A new update is available: version {v}', 'updates.download': 'Download update', 'updates.downloading': 'Downloading… {p}%', 'updates.downloaded': 'Version {v} downloaded – restart to install', 'updates.install': 'Restart & install', 'updates.upToDate': 'You are on the latest version', 'updates.checking': 'Checking…', 'updates.error': 'Could not check for updates: {e}', 'updates.disabledDev': 'Auto-update only works in the installed (exe) build.', 'updates.how': 'How do updates work?', 'updates.howText': 'At start-up the app checks the release server; when a newer version exists a notice appears here and at the top of the screen, and it can be downloaded and installed with one click without losing data.', 'updates.releaseNotes': 'Release notes', 'updates.later': 'Later',
    'workspace.title': 'Data & backup', 'workspace.dir': 'Data folder', 'workspace.records': 'Records', 'workspace.backup': 'Export full backup (JSON)', 'workspace.restore': 'Restore from backup', 'workspace.restoreMode': 'Restore mode', 'workspace.merge': 'Merge (keep existing records)', 'workspace.overwrite': 'Overwrite matching records', 'workspace.restored': '{n} records restored', 'workspace.error': 'The configured data folder is unreachable; the local folder is used temporarily: {e}', 'workspace.users': 'users', 'workspace.groups': 'groups', 'workspace.exams': 'exams', 'workspace.attempts': 'attempts', 'workspace.sessions': 'simulation sessions',
    'audit.title': 'Activity log', 'audit.action': 'Action', 'audit.by': 'By', 'audit.details': 'Details',
    'profile.title': 'My account', 'profile.changePassword': 'Change password', 'profile.old': 'Current password', 'profile.new': 'New password', 'profile.changed': 'Password changed', 'profile.mustChange': 'You must change your temporary password before continuing.', 'profile.group': 'Group', 'profile.sessions': 'My simulation sessions',
    'about.title': 'About', 'about.version': 'Version', 'about.data': 'Data sources', 'about.dataText': 'The plant database is based on the WRI Global Power Plant Database (v1.3.0, CC BY 4.0) plus curated recent plants (2019–2026) compiled from operator and utility publications (DEWA, EWEC, SEC, EEHC, MASEN, Nawah…), IRENA and press releases. Base map: Natural Earth (public domain). Font: Cairo (OFL).', 'about.disclaimer': 'Disclaimer', 'about.disclaimerText': 'This is an educational product. Simulation models are simplified and rely on typical parameters per technology, not live operating data; capacities and dates may differ from current reality. Not for any real operational use.', 'about.machine': 'Machine ID', 'about.workspace': 'Data folder', 'about.plants': 'Plants', 'about.techs': 'Supported technologies',
    'errors.bad_credentials': 'Wrong username or password', 'errors.not_authenticated': 'Please sign in', 'errors.forbidden': 'You are not allowed to do that', 'errors.username_taken': 'Username already exists', 'errors.invalid_username': 'Invalid username (3–64 latin letters or digits)', 'errors.weak_password': 'Password too short (min 6 characters)', 'errors.invalid_role': 'Invalid role', 'errors.not_found': 'Item not found', 'errors.last_superadmin': 'Cannot remove the last super admin', 'errors.license_required': 'Activate the license first', 'errors.already_setup': 'Setup already completed', 'errors.max_attempts': 'You have used all allowed attempts', 'errors.already_submitted': 'This attempt was already submitted', 'errors.title_required': 'Title is required', 'errors.name_required': 'Name is required', 'errors.bad_question_count': 'Invalid question count (1–200)', 'errors.bad_duration': 'Invalid duration', 'errors.bad_pass_mark': 'Invalid pass mark', 'errors.channel_not_allowed': 'Channel not allowed', 'errors.seats_exceeded': 'The license seat limit (number of accounts) has been reached', 'errors.module_locked': 'This module is not included in the license', 'errors.tech_locked': 'This technology is not included in the license', 'errors.bad_url': 'Invalid URL', 'errors.generic': 'Error: {e}',
  },
};

let current = 'ar';
const listeners = new Set();

export function t(key, vars) {
  let s = dict[current][key] ?? dict.en[key] ?? key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
  return s;
}
export function lang() { return current; }
export function isAr() { return current === 'ar'; }
export function setLang(l) {
  current = l === 'en' ? 'en' : 'ar';
  document.documentElement.lang = current;
  document.documentElement.dir = current === 'ar' ? 'rtl' : 'ltr';
  for (const fn of listeners) fn(current);
}
export function onLangChange(fn) { listeners.add(fn); return () => listeners.delete(fn); }
export function extend(extra) { for (const l of Object.keys(extra)) Object.assign(dict[l] || (dict[l] = {}), extra[l]); }
/** Picks the localised field of a data object: L(obj, 'name') -> obj.nameAr in Arabic when present. */
export function L(obj, base) {
  if (!obj) return '';
  if (current === 'ar') return obj[base + 'Ar'] || obj[base] || obj[base + 'En'] || '';
  return obj[base + 'En'] || obj[base] || obj[base + 'Ar'] || '';
}
/** Localised text from {ar, en} objects. */
export function LT(o) { return o ? (o[current] || o.en || o.ar || '') : ''; }
export function errorMessage(code) {
  const k = 'errors.' + code;
  return dict[current][k] ? t(k) : t('errors.generic', { e: code });
}
