'use strict';
/**
 * Vendor public keys embedded in the application.
 *
 * PRODUCTION_PUBLIC_KEY_PEM: generated by the vendor with `npm run license -- keygen` (this file is rewritten
 *   automatically and the private key is stored OUTSIDE git in tools/license-cli/keys/). Packaged builds accept
 *   only licenses signed with the matching private key.
 * DEV_PUBLIC_KEY_PEM: development key (private half committed in tools/license-cli/dev-keys/). Accepted ONLY
 *   when the app is not packaged (`electron .`), so developers can test activation. Never used in production builds.
 */
module.exports = {
  PRODUCTION_PUBLIC_KEY_PEM: null,
  DEV_PUBLIC_KEY_PEM: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAIew36+U0YCqK05Mbf/TgAHX1NBqnW9mq8iuLuY7idnc=\n-----END PUBLIC KEY-----\n",
};
